apiVersion: apps/vreplaceImageTag
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat-app
spec:
  replicas: replaceImageTag
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: application-server
        image: jeegan28/tomcat:replaceImageTag
        ports:
        - containerPort: replaceImageTag
          name: http

        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DB_PASS
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: DB_PORT


