apiVersion: v1
kind: Service
metadata:
  name: my-apache-service
spec:
  type: NodePort
  selector:
     app: web-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 30001

