pipeline {
    agent {
        docker {
           image 'abhishekf5/maven-abhishek-docker-agent:v1'
           args '-u root -v /var/run/docker.sock:/var/run/docker.sock' 
      }
   }
            
    environment {
        GIT_USER="Jeegan28"
        GIT_REPO="3-tier-architecture"
        DOCKER_CREDENTIALS=credentials('docker-cred')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: "https://github.com/${GIT_USER}/${GIT_REPO}.git"
            }
        }
        
        stage('Sync with remote') {
            steps {
                sh '''
                   git fetch origin main
                   git merge origin/main || git rebase origin/main
                '''   
            }
        }

        stage('build and push apache image') {
            environment {
                DOCKER_IMAGE="jeegan28/apache:${BUILD_NUMBER}"
            }
            steps {
                script {
                    sh '''
                        cd src
                        docker build -t ${DOCKER_IMAGE} -f Dockerfile_apache .
                    '''
                    def dockerImage = docker.image(env.DOCKER_IMAGE)
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('build and push tomcat') {
            environment {
                DOCKER_IMAGE="jeegan28/tomcat:${BUILD_NUMBER}"
            }
            steps {  
                script {
                    sh '''
                        cd src
                        docker build -t ${DOCKER_IMAGE} -f Dockerfile_tomcat .
                    '''
                    def dockerImage = docker.image(env.DOCKER_IMAGE)
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Replace build number in manifestfiles') {
            steps {
                withCredentials([string(credentialsId: "github", variable: "GITHUB_TOKEN")]) {
                    sh """
                        git config user.email "jeegan@xyz.com"
                        git config user.name "Jeegan Jaikumar"
                        sed -i "s/replaceImageTag/{BUILD_NUMBER}/g" manifest_files/Deployment_*.yml
                        echo "Build number is ${BUILD_NUMBER}"
                        if ! git diff --quiet; then
                          git add manifest_files
                          git commit -m "Update deploy version to ${BUILD_NUMBER}"
                          git push https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${GIT_REPO}.git HEAD:main
                        else
                          echo "No changes to commit"
                        fi
                    """
                }
            }
        }
    }
}


